### ISSUE TITLE
Quand on enregistre “un dossier en brouillon”, rester sur la page au lieu d’aller sur “mes dossiers”

### ISSUE THREAD

**Issue by gregoirenovel** [sgmap/tps#1011]
Comme quand on sauve sous Word

Engagement : CGDD

**Comment by fredZen** [comment]
@gregoirenovel tu sais si ça a encore du sens de communiquer ça au CGDD, et si oui à qui ? Si ça sert encore à quelque chose, je veux bien me charger d’écrire une bafouille et de l’envoyer, sinon je me contente d’enlever le _à communiquer_.

**Comment by gregoirenovel** [comment]
Je viens de leur mettre un petit email.
