### ISSUE TITLE
Augmenter la limite de taille des pj dont la somme ne peut actuellement dépasser 20Mo

### ISSUE THREAD

**Issue by icollombet** [sgmap/tps#104]
Objectif : 50 Mo, si c'est pas possible ou que ça pose des pbs techniques on en rediscute

**Comment by mmagn** [comment]
A faire avec la création d'un champ de formulaire de type PJ ?

**Comment by benjaminhenkel** [comment]
https://github.com/sgmap/tps/issues/173
