### ISSUE TITLE
Changer la méthode de génération de slugs

### ISSUE THREAD

**Issue by gregoirenovel** [sgmap/tps#109]
Utiliser `#parametrize` dans `Procedure#default_path`

Ex :
```ruby
"Ma belle procédure à remplir rapidement".parameterize
# => "ma-belle-procedure-a-remplir-rapidement"
```

Avantage : on garde les lettres avec accents (les accents sont dégagés) au lieu de les remplacer par des tirets, ce qui rend l'URL plus lisible.

**Comment by mmagn** [comment]
Done
