### ISSUE TITLE
ETQ Administrateur, je veux utiliser des champ du dossier dans les emails personnalisables

### ISSUE THREAD

**Issue by fredZen** [sgmap/tps#1110]
Attention à ne pas perdre les balises existantes (dont --motivation--)

**Comment by fredZen** [comment]
Devrait permettre de traiter #1040 dans la foulée

**Comment by gregoirenovel** [comment]
Fixed by #1173, #1174, 1175, 1176 and #1177 (original mega-PR: #1154)
