### ISSUE TITLE
Permettre à un accompagnateur d'ajouter un "collaborateur" à un dossier pour lui demander son avis

### ISSUE THREAD

**Issue by mmagn** [sgmap/tps#131]
Coté accompagnateur dans la vue détail d'un dossier, il est possible d'inviter des _collaborateurs_ à renseigner un avis sur le dossier.

Un formulaire d'invitation est composé, d'un champ email et un champ d'explication à destination de l'invité.

A la soumission, on créé un compte pour l'email s'il n'existe pas.

Quand un invité arrive sur un dossier il peut consulter le dossier, participer à la discussion, et remplir un avis dans un champ texte multiligne (à coté est affiché l'explication saisie par l'accompagnateur lors de l'invitation).

L'invité peut enregistrer son avis.

Coté accompagnateur on affiche la liste des invités avec leur avis associé si il est saisi.

TODO

- [x] Un accompagnateur doit pouvoir demander un avis sur la page de détails d'un dossier
- [x] Lister les Avis dans la page dossier Accompagnateur
- [x] Un accompagnateur invité pour avis sur un dossier ne doit pas pouvoir voir les autres avis, changer l'état d'un dossier, voir le formulaire privé
- [x] Un accompagnateur invité pour avis sur un dossier doit pouvoir laisser son avis
- [x] Envoyer un email pour notifier de la demande d'avis

**Comment by MarineCrespel** [comment]
- Un accompagnateur demande l'avis d'un invité
 => https://invis.io/UABFYL8RJ#/230611641_1A-Avis_Invites

- Un donne son avis
 => https://invis.io/UABFYL8RJ#/230612299_6-Invites_Connexion

**Comment by gregoirenovel** [comment]
À communiquer : Ansm, educ nat.
