### ISSUE TITLE
Supprimer tout lien vers la plateforme d'inté

### ISSUE THREAD

**Issue by gregoirenovel** [sgmap/tps#160]
C'est une plateforme de recette, pas de démo.

Pré-requis : #76, #77

**Comment by emsnytech** [comment]
Il faut alors créer une plate forme de démo. La plate forme de prod a toujours du retard. Par ailleurs on ne peut faire de démonstration sur la plate forme de prod avec France Connect sans utiliser des comptes réels. Si on ne peut ne plus faire apparaitre les démarches archivées dans la liste des démarches quand on est accompagnateurs, énorme risque de pollution. Je reste un partisan d l'utilisation de la plate forme de dev comme plate forme de formation. Donc proposition de créer une troisième instance que pour la recette et garder la plate forme de Dev, qui devient une plate forme de formation.
