### ISSUE TITLE
Possibilité d'éditer des attestations

### ISSUE THREAD

**Issue by icollombet** [sgmap/tps#196]
Un grand nombre de démarches administratives aboutissent à la délivrance d'une attestation qu'il faut souvent présenter à un autre organisme administratif (sic) [et pour l'instant, on n'arrive pas à en convaincre certains, comme les douanes, de venir regarder directement l'issue d'une procédure sur TPS] + il existe souvent déjà des outils pour éditer des certificats et s'il faut que les types ressaisissent ce qui a déjà été saisi sur TPS c'est débile.

D'où le développement d'un module d'édition d'attestations.

Caractéristiques :
- module type "e-mail personnalisable" actuel + balises permettant de remonter toutes les valeurs des champs ainsi que les données d'identités particuliers ou entreprise + la motivation + possibilité de mettre des images
- possibilité de convertir le template en pdf et de l'envoyer en pj des emails (tous)

**Comment by MarineCrespel** [comment]
@ivancollombet :thumbsup:

**Comment by icollombet** [comment]
@marinecrespel1 nope

**Comment by MarineCrespel** [comment]
@ivancollombet @mathieumagnin @simonlehericey @gnovel est-ce utile que je fasse la prévisualisation du PDF d'attestation ?

**Comment by MarineCrespel** [comment]
Usager : 
Détail dossier => Ajouter un bloc attestation 
Lien invision => https://invis.io/UABFYL8RJ#/230612373_3A-Attestation_Recue_-usager-

**Comment by MarineCrespel** [comment]
Accompagnateur : 
Détail dossier => Popin acceptation à modifier avec possibilité de voir l'attestation
Lien invision => https://invis.io/UABFYL8RJ#/230612312_2A-Attestation_Acceptation_-accompagnateur-

**Comment by MarineCrespel** [comment]
Administrateur :
Onglet emails => Ajouter un item de menu "attestation" + principe de switch activer/désactiver
 Lien invision ici => https://invis.io/UABFYL8RJ#/230612309_1A-Attestation_Edition

**Comment by icollombet** [comment]
@marinecrespel1 on pourra en discuter 5 mns ensemble ?

**Comment by gregoirenovel** [comment]
Mettre un lien vers l'attestation sur dossier une fois qu'elle est générée
