### ISSUE TITLE
Notification hebdomadaire des accompagnateurs par email

### ISSUE THREAD

**Issue by emsnytech** [sgmap/tps#199]
Proposer un récapitulatif des dossiers déposés / modifiés au cours de la semaine précédente qui permettent :
1. aux accompagnateurs qui vont rarement sur TPS de savoir s'ils ont des nouveautés
2. aux accompagnateurs qui vont souvent sur TPS d'avoir des informations sur leurs activités de la semaine passée.
Prévoir un mécanisme de désabonnement

**Comment by icollombet** [comment]
Une fois par semaine, on envoie aux accompagnateurs un email récpaitulatif : sur telle procédure, x nouveau dossiers, x modifications dans les dossiers que vous suivez... + présenter le truc comme quelque chose de statistique

**Comment by gregoirenovel** [comment]
Pas de paramétrage, une routine tous les dimanches soir avec un récap global de la vue Accompagnateur.

**Comment by emsnytech** [comment]
Deux options proposées: soit au moment de la création d'une démarche, paramétrage de la fréquence de réception a chaque motif, une fois par jours...,ou paramétrage au sein même d'un profil de l'accompagnateur.
Priorité 1, car blocage du côté des services...

**Comment by gregoirenovel** [comment]
Closed by #294
