### ISSUE TITLE
Accompagnateur Invité : Améliorer l'UI d'invitation d'accompagnateur

### ISSUE THREAD

**Issue by LeSim** [sgmap/tps#201]

**Comment by LeSim** [comment]
voir https://projects.invisionapp.com/share/EDAVZVNS7#/screens/227310886 et suivant

**Comment by MarineCrespel** [comment]
@simonlehericey Nouveau lien => https://invis.io/UABFYL8RJ#/230612268_1-Invites

**Comment by emsnytech** [comment]
Yes. Prévoir la possibilité de retirer l'invitation.
