### ISSUE TITLE
Accompagnateur Invité :  ref: Distinguer les statuts "usager invité" et "accompagnateur invité"

### ISSUE THREAD

**Issue by icollombet** [sgmap/tps#202]
Pour l'instant, un seul statut pour les invités, qu'ils soient invités par les usagers ou les accompagnateurs, offrant les mêmes droits que l'usager. Objectif = créer un nouveau statut pour les personnes invitées par les accompagnateurs permettant de co-instruire les dossiers.

Caractéristiques de l' "accompagnateur invité" proposées :
- mécanisme d'invitation de l'accompagnateur invité semblable à aujourd'hui
- email de l'accompagnateur invité non visible par l'usager et ses invités
- mêmes droits que l'accompagnateur principal sauf : pas de possibilité de changer le statut du dossier ("passer en instruction, archivé...")

Coté accompagnateur, montrer les invités de l'usager.

**Comment by icollombet** [comment]
@marinecrespel1  on pourra en discuter 5 mns ensemble ?

**Comment by MarineCrespel** [comment]
Questions
=> Affiche-t-on la liste des invités de l'usager ?
=> Laisse-t-on le droit d'ajouter ou supprimer des invités à un accompagnateur qui ne suit pas le dossier ? 
=> Est-ce qu'un accompagnateur qui suit le dossier peut supprimer un autre accompagnateur ? 
=> Est-ce qu'on ajoute la notion de liste de dossiers pour un inviter d'un accompagnateur ?

**Comment by MarineCrespel** [comment]
Proposition d'amélioration : 
- Ne laisser la possibilité qu'aux accompagnateurs qui suivent le dossier d'ajouter ou supprimer des invités et accompagnateurs
- Faire une seule liste mêlant invités et accompagnateurs
- Ajouter des statuts : droits complet (accompagnateurs) droits partiels (invités) en attente de réponse (accompagnateurs ou invités sans réponse)
- Améliorer l'email d'invitation : 
ajouter le logo TPS
ajouter lien vers la landing (pour plus d'infos)
mettre un CTA pour accéder au dossier

**Comment by MarineCrespel** [comment]
Utiliser le même composant que l'écran de gestion des accompagnateurs sur la plateforme administrateur, mais en pop-in. (nouveau design)
[4-invites.jpg](https://trello-attachments.s3.amazonaws.com/52b0574a8a3a8fd37a00fc6d/58b53b82e55908fedf4eeb5a/e54611a95ed16220ac0d7fb1e13c4199/4-invites.jpg) [3-invites.jpg](https://trello-attachments.s3.amazonaws.com/52b0574a8a3a8fd37a00fc6d/58b53b82e55908fedf4eeb5a/6c9a49ba5ec5acfb30d4defc1c772214/3-invites.jpg) [2-invites.jpg](https://trello-attachments.s3.amazonaws.com/52b0574a8a3a8fd37a00fc6d/58b53b82e55908fedf4eeb5a/fb9f2574dd97ef97ee866328e2743b3e/2-invites.jpg) [1-invites.jpg](https://trello-attachments.s3.amazonaws.com/52b0574a8a3a8fd37a00fc6d/58b53b82e55908fedf4eeb5a/ba5af4d10655063caf7ede92be92f8eb/1-invites.jpg) 
Disponible aussi sur Zeplin

**Comment by MarineCrespel** [comment]
Lien invision ici => https://projects.invisionapp.com/d/main#/console/10550968/227310886/preview

**Comment by gregoirenovel** [comment]
@marinecrespel1 My bad, je les transfère

**Comment by MarineCrespel** [comment]
@gnovel Pas de souci je ne l'avais pas donné. Je te répondrais sur invision du coup.

**Comment by emsnytech** [comment]
@marinecrespel1 est ce que tu pourrais me donner des droits d'accès sur invision, j'ai déjà un compte. TB tes propositions !

**Comment by MarineCrespel** [comment]
@vrignaud1 est-ce que tu peux me donner tes identifiants ?

**Comment by MarineCrespel** [comment]
Modifications :

- Pop-in invitation 
Afficher 1 liste avec 3 profils : accompagnateurs/accompagnateurs invités/usagers invités 

Ajouter la possibilité d'envoyer un message personnalisé

Retirer la possibilité de supprimer un accompagnateur invité

Remplacer titre par "Inviter une personne à co-instruire le dossier" côté usager "Inviter une personne à co-élaborer le dossier"

Remplacer le texte du bouton par "personnes impliquées"

Ajouter message d'erreur & bloquer envoie d'invitation pour usager/accompagnateur/déjà invité

Retirer btn "réinitialiser"


- Email :
Modifier template = 1 seul lien + identifiants (si pas de compte)
"Vous avez invité à..."


- Interface invité :
Connexion : vue dossier avec même droits accompagnateur (sauf "passer en instruction") => suivre le dossier par défaut 

Tableau de bord accompagnateur : onglet invitation

Détail invitation : reprise vue liste dossier usager +  ajouter colonne action "ne plus suivre"/"suivre" + Titre "invitation" + retirer btn "modifier..." "télécharger..."

**Comment by MarineCrespel** [comment]
Tous les écrans ici => https://invis.io/UABFYL8RJ#/230612268_1-Invites
Et sur Zeplin bien sûr !
