### ISSUE TITLE
Accompagnateur Invité : cas accompagnateur TPS

### ISSUE THREAD

**Issue by LeSim** [sgmap/tps#205]
- [ ] Changer le wording du mail d'invitation : la personne connait TPS
- [ ] Changer le lien vers le dossier pour ne pas passer par une mire d'inscriptionY
- [ ] Retirer le mécanisme de confirmation d'invitation (?)
- [ ] Ajouter une partie invitation dans le menu de droite qui mene à la liste des dossiers
- [ ] Ajouter une vue sur ces dossiers pour avec résumé du dossier + édition de champs privés

**Comment by LeSim** [comment]
Si l'acc invité est déjà membre TPS.

L'acc invité peut consulter la liste des dossiers sur lequel il est invité depuis sa vue récapitulative.

Les invitations sont regroupés sous un onglet à gauche
https://projects.invisionapp.com/share/EDAVZVNS7#/screens/229660222

De la, l'acc invité peut consulter le récapitulatif d'un dossier et compléter ces champs privés

**Comment by mmagn** [comment]
Pour récupérer la liste des Administrateur à contacter pour tester les avis externe sur tps-dev : 
```
emails_gestionnaires = Invite.where(type: InviteGestionnaire).group(:email_sender).count.select { |k,v| v> 9 }.keys
Gestionnaire.where(email: emails_gestionnaires).map(&:administrateurs).flatten.map(&:email).uniq
```

**Comment by gregoirenovel** [comment]
À communiquer : France Agrimer
