### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by icollombet** [sgmap/tps#206]

**Comment by MarineCrespel** [comment]
Cible administrateur

1- Accroche : Dématérialiser vos démarche administrative en quelques minutes

Avantages : 
- Construire sa démarche en ligne
- Gérer les demandes des usagers sur la plateforme
- Collaborer pour construire et instruire les demandes à plusieurs

(voir => https://beta.gouv.fr/startup/tps.html)

Bouton d'entrée sur la plateforme
1- Nouveau => programmer démo
2- J’utilise TPS => connexion

Fonctionnalités
Captures d’écrans des fonctionnalités ?

Crédibilité
=> Un produit de l’état
=> Mettre logo des partenaires et utilisateurs
=> Témoignage utilisateur (+chiffres)

**Comment by icollombet** [comment]
Nb de procédures dématérialisées
