### ISSUE TITLE
Quand un dossier est archivé, il n'est plus visible par l'usager

### ISSUE THREAD

**Issue by icollombet** [sgmap/tps#207]

**Comment by LeSim** [comment]
@ivancollombet je comprends pas trop.

Tu me confirmes que :
lorsqu'un accompagnateur valide un dossier
puis l'archive pour ne plus être pollué 
le dossier ne doit pas apparaître dans la catégorie terminé de l'usager ?

Le dossier ne doit plus être visible par l'usager ?

**Comment by icollombet** [comment]
@simonlehericey non je constatais seulement un bug : figure toi que quand un accompagnateur archive un dossier x d'un utilisateur y, le dosssier x disparaît tout simplement de la liste des dossiers de l'utilisateur y
