### ISSUE TITLE
En tant qu'administrateur je veux pouvoir rendre une pièce jointe obligatoire lors de la construction de mon formulaire

### ISSUE THREAD

**Issue by icollombet** [sgmap/tps#209]
Il faut, pour chaque pièce jointe, donner la possibilité de rendre cette pièce jointe obligatoire.

Lorsque l'utilisateur remplissant le formulaire ne renseigne pas les pièces obligatoires, afficher une erreur.

**Comment by icollombet** [comment]
Bloque quand l'usager esssaie de soumettre sa demande

**Comment by mmagn** [comment]
à voir si on peut toujours enregistrer en brouillon, s'il manque des infos obligatoires
