### ISSUE TITLE
Autoriser tous types d'url pour les procédures - notamment les tirets

### ISSUE THREAD

**Issue by icollombet** [sgmap/tps#212]
nous voulions créer une télé-procédure avec un nom comprenant des tirets ( - ); or, nous venons de nous rendre compte que le nom "doit comporter au moins 3 caractères et seuls les caractères a-z, 0-9 et '_' sont autorisés." Le tiret semble donc exclu.

**Comment by mmagn** [comment]
Autoriser les tirets dans les urls, voir si on peut changer la génération automatique des slugs : underscore => dash
