### ISSUE TITLE
Champ n° dossier

### ISSUE THREAD

**Issue by icollombet** [sgmap/tps#213]

**Comment by icollombet** [comment]
quand un administrateur crée un formulaire, il peut insérer un nouveau type de champ donnant la possibilité à l'usager de rentrer un "n° dossier" - et si l'usager a accès à ce dosssier (usager ou invité ou accompagnateur), tps remonte les informations concernant le dossier et ensuite tout les intervenants sur le dossier.

**Comment by mmagn** [comment]
Sur la vue usager : remonter quelques infos qui permettent d'identifier facilement le dossier (dans la v0, aucune infos, juste un champ texte)

Sur la vue accompagnateur : afficher un lien, qui mène au dossier

**Comment by icollombet** [comment]
@simonlehericey @gnovel fonctionnel mais rudimentaire je pense qu'on peut faire mieux pour pas cher : cf. ci-dessus.

**Comment by icollombet** [comment]
1. A minima : écrire
Ce dossier a été déposé sur la procédure "[titre de la procédure]".

2. Encore mieux :
Ce dossier a été déposé le [date de soumission en français] sur la procédure "[titre de la procédure]" gérée par l'organisme [nom de l'organisme].

**Comment by icollombet** [comment]
Du coup j'ai fait une nouvelle carte avec ces suggestions d'amélioration
