### ISSUE TITLE
Page de stats publique

### ISSUE THREAD

**Issue by gregoirenovel** [sgmap/tps#214]

**Comment by emsnytech** [comment]
j'ai l'impression que les stats sont revenu à 0....

**Comment by icollombet** [comment]
@gnovel tu peux mettre l'url, stp ?

**Comment by gregoirenovel** [comment]
C'est dans le footer.

En dev : https://tps-dev.apientreprise.fr/stats

**Comment by emsnytech** [comment]
Excellent !  merci
