### ISSUE TITLE
Wording

### ISSUE THREAD

**Issue by icollombet** [sgmap/tps#218]

**Comment by icollombet** [comment]
@simonlehericey il faudrait corriger encore 2 trucs de "wording"
1/ les sélecteurs de date sont en anglais (page d'identification dans le cas particulier pour la sélection de la date de naissance USAGER + page de planification de l'archivage de la procédure ADMIN) => si on peut désactiver le sélecteur et mettre seulement JJ/MM/AAAA ce serait parfait
2/ pour les invités, le dropdown qui s'affiche quand on clique sur "voir les personnes impliquées, il y a encore "Title" et "Empty" quand il n'y a personne d'invité USAGER + ACCOMPAGNATEUR

**Comment by LeSim** [comment]
@ivancollombet je fais une nouvelle carte parce que c'est pas du jeu de changer les specs en cours de route ...
