### ISSUE TITLE
Erreur de décompte des notifications

### ISSUE THREAD

**Issue by mmagn** [sgmap/tps#245]
voir le mail d'Ivan du 3 mai 2017

>À la connexion en tant qu'accompagnateur, il est indiqué 2 notifications à la procédure
 Mais quand on clique sur notifications, il n'y en a aucune.
Comme on doit répondre à toutes les notifications, s'agit-il d'une erreur d'affichage sur le nombre ou d'accès aux notifications ?

![unnamed](https://cloud.githubusercontent.com/assets/847942/25694014/ab4b9666-30ac-11e7-8f14-816d41118a4e.png)

**Comment by LeSim** [comment]
@mmagn @gregoirenovel 

Alors j'ai l'impression que ça se joue là.
app/views/layouts/left_panels/_left_panel_backoffice_dossierscontroller_index.html.haml

le problème semble être que les notifications affichées derrière le bouton Notifications sont uniquement celles sur les dossiers que je suis.

Alors que les ronds rouges affichés à droite des noms des dossiers sont les notifications sur les dossiers, qu'on les suive ou non.

==> it's not a bug, it's a feature.

Votre avis ?

**Comment by mmagn** [comment]
J'ai surement merdé, quand j'ai retiré la facade. Je regarde en détails pour voir.

**Comment by gregoirenovel** [comment]
Probablement remonté directement par Ivan, pas par un utilisateur
