### ISSUE TITLE
Ajouter l’inscription à la newsletter dans le footer

### ISSUE THREAD

**Issue by mmagn** [sgmap/tps#263]
Voir si mailjet n'a pas un truc tout prêt.

**Comment by gregoirenovel** [comment]
Fixed by #269

**Comment by emsnytech** [comment]
Je n'arrive pas à le faire fonctionner en dev...

**Comment by gregoirenovel** [comment]
Idem, sous le dernier FF, il ne se passe rien quand on clique.

**Comment by gregoirenovel** [comment]
Corrigé par #308
