### ISSUE TITLE
Amélioration de la page /stats

### ISSUE THREAD

**Issue by mmagn** [sgmap/tps#264]
Objectif de la page : Transparence sur l'utilisation de l'application
Cartes à développer :
- Barre de progression % de complétion de la dématérialisation des démarches pour les entreprise, valeur : 2,5% (source : rapport Dîtes-le nous une fois)
- Column chart : Nouvelles démarches dématérialisées / mois sur les 3 derniers mois.
- Column chart : Nouveaux dossiers déposés / mois sur les 3 derniers mois.
- Pie chart : Nombre d'administrations ayant dématérialisé : 
  - 1 procédure
  - 2 à 5 procédures
  - +5 procédures
- Line chart : Temps de traitement moyen / procédure
- Line chart : Temps mis en moyenne par un usager pour remplir une procédure de 10 champs

**Comment by gregoirenovel** [comment]
> Barre de progression % de complétion de la dématérialisation des démarches pour les entreprise, valeur : 2,5% (source : rapport Dîtes-le nous une fois)

Je ne vais pas le faire pour plusieurs raisons :
- Ce n'est pas une métrique qui concerne uniquement TPS, donc elle ne représente que partiellement notre impact
- On va très rarement mettre à jour sa valeur, donc intérêt faible si on ne voit pas la progression
- Chartkick ne permet pas de faire de barre de progression

**Comment by mmagn** [comment]
Ok pour le point 2 la maj va être trop fastidieuse et la métrique est imprécise => on drop la carte.
Les autres points sont discutables :)
