### ISSUE TITLE
Uniformiser les signatures des emails text

### ISSUE THREAD

**Issue by mmagn** [sgmap/tps#274]
```
---
L'équipe (parfois équide) TPS - contact@tps.apientreprise.fr (parfois tps@apientreprise.fr)

```
deviens

`L'équipe Téléprocédures Simplifiées - contact@tps.apientreprise.fr
`

**Comment by gregoirenovel** [comment]
Ne pas changer que la signature, changer aussi l'email avec laquelle on envoie les emails (actuellement `tps@entreprise.fr`)

**Comment by gregoirenovel** [comment]
On veut pas juste signer avec `L'équipe Téléprocédures Simplifiées` ? L'adresse email est déjà dans le champ "expediteur", ça me semble redondant de le remettre ici
