### ISSUE TITLE
Icone "bouclier" sur Chrome

### ISSUE THREAD

**Issue by gregoirenovel** [sgmap/tps#295]
![screen shot 2017-05-16 at 10 13 23](https://cloud.githubusercontent.com/assets/1333173/26096099/5e38c3a8-3a20-11e7-9dee-b810edcaaa84.png)

"This page is trying to load scripts from unauthenticated sources"

Je pense que c'est du au script Mailjet qui est en HTTP alors que notre site est servi en HTTPS

**Comment by LeSim** [comment]
Bien vu, je corrige rapidement
