### ISSUE TITLE
Refaire l'export conformément à l'ordre des données d'un dossier

### ISSUE THREAD

**Issue by gregoirenovel** [sgmap/tps#315]
Particulièrement après un clone de procédure

**Comment by benjaminhenkel** [comment]
Pauline Garino

**Comment by benjaminhenkel** [comment]
Mayenne

**Comment by benjaminhenkel** [comment]
J'ai quand même plusieurs retours usagers dans ce sens, et c'est vrai que ça me paraît tout de même peu pratique que ce soit dans un ordre aléatoire

**Comment by mmagn** [comment]
Le problème est surtout pour les champs custom du formulaire non ?

**Comment by benjaminhenkel** [comment]
oui, tout à fait !

**Comment by benjaminhenkel** [comment]
C'est long à faire, selon toi?

**Comment by benjaminhenkel** [comment]
Nouveau retour : Ministère des Solidarités et de la santé 

Assez grave pq du coup ne peuvent pas faire de Macro, d'où priorisation

**Comment by gregoirenovel** [comment]
Je pense que cette issue est en fait 2 issues :
- d'une part l'ordre des champs publics et privés dans l'export
- d'autre part l'ordre des colonnes dans l'export (champs publics / champs privés / données d'identité / metadata du dossier...)

**Comment by mmagn** [comment]
Oui le premier c'est un bug prioritaire, le deuxième un nice to have.

**Comment by mmagn** [comment]
on garde le bug dans celle là ?

**Comment by gregoirenovel** [comment]
Issue originale déplacée dans #614
