### ISSUE TITLE
ETQ usager je ne suis pas prévenu des mail d'AR

### ISSUE THREAD

**Issue by emsnytech** [sgmap/tps#339]
ADICO a fait remonter le pb que depuis que les mails d'AR sont portés dans le flux de messagerie, il n'y aurait plus de mail d'AR envoyé à l'usager.

**Comment by gregoirenovel** [comment]
C'était un problème dans Mailjet, non lié à la copie des messages dans le flux de messagerie, c'est désormais rectifié
