### ISSUE TITLE
Bug Avis : NoMethodError in Users::Recapitulatif#show

### ISSUE THREAD

**Issue by gregoirenovel** [sgmap/tps#375]
Créer un dossier, le faire instruire jusqu'au bout (accepté).

En tant qu'usager, aller voir ce dossier, ça crash :

Showing /Users/gregoirenovel/Development/tps/app/views/dossiers/_avis.html.haml where line #47 raised:
`undefined method `model_name' for nil:NilClass`, 

**NB :** ça arrive quand on a un compte multi-profils gestionnaire + user, et que sur ce dossier, on est est **à la fois** user et gestionnaire

**Comment by mmagn** [comment]
Fixed with https://github.com/sgmap/tps/commit/c185f60dd2ff2c3488bb2f679bddb79f049ce933
