### ISSUE TITLE
Homogénéiser le format des champs date dans l'API

### ISSUE THREAD

**Issue by icollombet** [sgmap/tps#376]
![image003](https://cloud.githubusercontent.com/assets/18182552/26620806/97f3104c-45e4-11e7-858b-a13fe7902fb1.png)
![image002](https://cloud.githubusercontent.com/assets/18182552/26620807/97f6b21a-45e4-11e7-9bcd-34ff8e137646.png)
![image001](https://cloud.githubusercontent.com/assets/18182552/26620808/97f6f018-45e4-11e7-9625-076d68606d89.png)

**Comment by gregoirenovel** [comment]
Double problème :

1. Pour différents champs de type "date", parfois on retourne des dates au format `YYYY-MM-DD`, parfois des dates au format `DD/MM/YYYY` (donc séparateurs et ordres différents)
2. Le format des timestamps est différent des champs de type "date"

**Comment by mmagn** [comment]
Engagement pour le 06/06

**Comment by gregoirenovel** [comment]
À communiquer : France Agrimer

**Comment by mmagn** [comment]
Les formats des valeurs stockées dans les types de champs date dépendent du support de `input type=date` des navigateurs (soit ISO `yyyy-mm-dd`, soit n'importe quoi).

Pour sortir dans l'API une date clean il faut : 
- [ ] faire tourner un script qui passe toutes les dates dans le format ISO
- [ ] cleaner manuellement le reste des données dans des formats exotiques (une vingtaine)

Pour éviter à nouveau la pollution des données il faut :
- [ ] autoriser aux utilisateurs de saisir uniquement au format ISO et `dd/mm/yyyy`
- [ ] effectuer un formatage au `before_save` pour passer au format ISO
