### ISSUE TITLE
Exporter l'email de connexion du demandeur dans "Télécharger tous les dossiers" et l'API

### ISSUE THREAD

**Issue by icollombet** [sgmap/tps#395]
Aujourd'hui, les accompagnateurs ne peuvent pas exporter en tableur (csv, xls, odt) les emails avec lesquels les usagers se sont connectés, alors que cela pourrait notamment être utile pour relancer une nouvelle campagne. Demande de l'Agence France Entrepreneur.

**Comment by benjaminhenkel** [comment]
https://github.com/sgmap/tps/issues/630

**Comment by benjaminhenkel** [comment]
A Débat public

**Comment by benjaminhenkel** [comment]
peut être mettre la colonne email à la fin dans le CSV? (éviter les pbs de macro)
