### ISSUE TITLE
Bug dans la partie cartographie

### ISSUE THREAD

**Issue by LeSim** [sgmap/tps#432]
Nous avons eu une détection d'alerte importante par NewRelic sur des not found. Ces erreurs ne sont pas remonté par Sentry qui ignore les not found par défault.

Stack Trace:
ActiveRecord::RecordNotFound: ActiveRecord::RecordNotFound 

…ww/tps/releases/86/app/controllers/users_controller.rb:  15:in `current_user_dossier'
…/releases/86/app/controllers/users/carte_controller.rb:  34:in `get_position'
…r/rails_ext/action_controller/metal/instrumentation.rb:  34:in `block in process_action'

On suppose que l'appel initial vient de carte.js, fonction get_position ligne 120.

En attente de plus d'information pour débugguer ce pb.

**Comment by gregoirenovel** [comment]
On en prend un nombre délirant en prod
