### ISSUE TITLE
Bug dans l'export avec CSV

### ISSUE THREAD

**Issue by benjaminhenkel** [sgmap/tps#435]
Comme le séparateur de ce format est la virgule, si jamais un champs contient une virgule, cela décale tout et rend le fichier inutilisable 

solution : il semble qu'il suffise de mettre des guillemets au sein des champs

**Comment by benjaminhenkel** [comment]
DPMA

**Comment by gregoirenovel** [comment]
L'export CSV marche correctement : les champs qui contiennent des virgules sont entourés de guillemets.

Par contre Excel ne sait pas importer correctement un CSV, il faut sélectionner le tableau puis aller dans Données -> "Text to column" / Convertir puis choisir "Délimiteur" et indiquer que des virgules sont le délimiteur.
