### ISSUE TITLE
Message d'erreur à la connexion administrateur et gestionnaire (démo)

### ISSUE THREAD

**Issue by MarineCrespel** [sgmap/tps#468]
_Intention initiale :_ 
Je souhaite me connecter à la plateforme de test en tant qu'administrateur et gestionnaire. 
Je ne rencontre pas le même problème avec la plateforme usager. 

_Ce que j'ai fais :_ 
J'ai cliqué sur les liens suivant : 
- https://tps-dev.apientreprise.fr/administrateurs/sign_in/demo
- https://tps-dev.apientreprise.fr/gestionnaires/sign_in/demo

_Résultat obtenu :_ 
Une page d'erreur s'affiche avec comme message : "We're sorry, but something went wrong."

_Résultat attendu :_ 
Arriver sur la page de connexion.

![capture d ecran 2017-06-20 a 14 30 13](https://user-images.githubusercontent.com/26059896/27333129-2269d784-55c5-11e7-908d-6b8a03550827.png)

**Comment by mmagn** [comment]
Belle description bravo @MarineCrespel.
