### ISSUE TITLE
Licence + questions

### ISSUE THREAD

**Issue by JulianNacci** [sgmap/tps#48]
Bonjour,

Je ne vois pas de fichier de licence dans le repo, quels sont vos projets à ce sujet ?
Projetez-vous de déployer une super instance ou que chaque collectivité self-host son app ?
Par ailleurs où en est le projet niveau gouvernance ? Est-il testé en production ?

PS : je représente une startup qui dev une plateforme en rails à destination des collectivités
http://bit.ly/publidata-pitchdeck-short

Merci de votre réponse,

Julian

**Comment by mmagn** [comment]
Bonjour Julian,

Merci pour ta question, nous venons d'ajouter la licence AGPL-v3 au repository.
Téléprocédure Simpligiée est déjà utilisé par des administrations et est accessible à l'adresse suivante https://tps.apientreprise.fr/ .
Ce projet est développé par l'incubateur de services numériques du Secrétariat Général de la Modernisation de l’Action Publique, plus d'infos sont disponibles sur https://beta.gouv.fr/ .

N'hésite pas si tu as d'autres interrogations.

Mathieu
