### ISSUE TITLE
Permettre aux administrateurs de modifier l'attestation une fois la procédure publiée.

### ISSUE THREAD

**Issue by icollombet** [sgmap/tps#491]
Aujourd'hui, l'attestation est figée une fois que la procédure publiée alors que les administrateurs peuvent avoir besoin de la changer (ex. correction de coquilles, évolution des textes réglementaires...). Demande de l'ANFR.

**Comment by LeSim** [comment]
ok.

On n'est d'accord que les changements sur le template d'attestation n'affecteront pas les attestations déjà émises ?
