### ISSUE TITLE
Permettre aux accompagnateurs de voir l'attestation qui a été envoyée aux usagers

### ISSUE THREAD

**Issue by icollombet** [sgmap/tps#492]
Aujourd'hui, les accompagnateurs voient un onglet attestation avec bouton télécharger dans le dossier en ligne mais ils n'ont pas accès à l'attestation lorsqu'ils cliquent sur le bouton ("The page you were looking for doesn't exist.") et pensent de ce fait qu'il y a un bug. Retour de France Agrimer.

**Comment by LeSim** [comment]
Je n'ai pas réussi à reproduire ce bug. Par contre j'ai isolé celui-ci qui est arrivé sur une attestation france agrimer #499.
