### ISSUE TITLE
Ajouter l'info si le SuperAdmin est connecté dans le header 

### ISSUE THREAD

**Issue by mmagn** [sgmap/tps#494]
+ bouton déconnexion SuperAdmin

**Comment by gregoirenovel** [comment]
Je propose qu'on refactor au passage le fonctionnement du Superadmin que je trouve particulièrement compliqué. Pourquoi on en ferait pas un "role" comme User / Gestionnaire / Admin ?

**Comment by mmagn** [comment]
Je pense qu'on peut faire la partie cosmétique avec cette issue, et la plomberie sur #496
