### ISSUE TITLE
Intégrer le GEOJSON et les informations remontées des contours réalisés sur la carte dans l'API

### ISSUE THREAD

**Issue by emsnytech** [sgmap/tps#508]
Pour lancer le dispositif "étude d'impact" il convient d'ajouter le geoJSON dans l'API.
Cela concerne deux autres procédure dans le pipe ( Permis de construire et ICPE min de la défense.

**Comment by CAEck** [comment]
Comme évoqué avec Ph. Vrignaud, ce point est crucial pour déploiement de la solution "Etudes d'impacts/Enquêtes publiques" du MTES.

**Comment by LeSim** [comment]
- étape préalable : modifier le modèle pour que la cartographie soit un champ de dossier

sinon l'api va être cassée lors du changement.
Impossible de modifier l'api en avance de phase car absence des données type_de_champ (id, libelle, order_place) ...

**Comment by CAEck** [comment]
Bonjour,
Auriez-vous une date quant à la mise en oeuvre du GéoJSON sur l'API TPS svp ?
Par avance, merci.
Cordialement,
Cyril AECK
