### ISSUE TITLE
Lors de l'export, il faudrait que dans le fichier excel, les colonnes soient organisées dans le même ordre que celui des champs du formulaire

### ISSUE THREAD

**Issue by benjaminhenkel** [sgmap/tps#518]
Cela peut poser certains soucis

**Comment by benjaminhenkel** [comment]
Pauline Garino

**Comment by emsnytech** [comment]
Bon, pas essentiel à mon avis....

**Comment by benjaminhenkel** [comment]
#315

**Comment by mmagn** [comment]
@benjaminhenkel le problème ce n'est pas que l'ordre des colonnes est aléatoire, il change quand la procédure est clonée ?
