### ISSUE TITLE
Faute de frappe à rectifier 

### ISSUE THREAD

**Issue by benjaminhenkel** [sgmap/tps#528]
![capture d ecran 2017-07-03 a 17 09 08](https://user-images.githubusercontent.com/28590367/27798698-7fb98ebe-6012-11e7-90bf-d8c453e36978.png)

**Comment by benjaminhenkel** [comment]
status==> statut

**Comment by gregoirenovel** [comment]
Le problème plus embetant c'est que ce message est incompréhensible et que le code est spaghetti comme il faut
