### ISSUE TITLE
Enlever le bouton "Contact" lorsque je remplis un formulaire ETQ utilisateur

### ISSUE THREAD

**Issue by benjaminhenkel** [sgmap/tps#532]
![capture d ecran 2017-07-04 a 10 29 47](https://user-images.githubusercontent.com/28590367/27821787-d3d39a6c-60a3-11e7-9b37-4cc2e07e9bdf.png)

**Comment by benjaminhenkel** [comment]
En bas de la page

**Comment by gregoirenovel** [comment]
Pourquoi ?

**Comment by gregoirenovel** [comment]
Superseded by #587
