### ISSUE TITLE
ETQ administrateur, lors de la création de mon formulaire, "The page you were looking doesn't exist" apparaît à plusieurs reprises

### ISSUE THREAD

**Issue by benjaminhenkel** [sgmap/tps#548]
Quand je suis en train de remplir des champs, au moment d’enregistrer ou de faire remonter un champ en haut de page, la page disparait pour afficher toujours ce même message « The page you were looking doesn’t exist ».

**Comment by benjaminhenkel** [comment]
Je vous communiquerai les identifiants, si nécessaire

**Comment by benjaminhenkel** [comment]
Ne semble plus être le cas (retour utilisateur INDS)

**Comment by gregoirenovel** [comment]
Pas reproduit non plus
