### ISSUE TITLE
ETQ utilisateur, lorsque je suis sur la page d'identification, il n'y a pas de contrôle de format de ma date de naissance

### ISSUE THREAD

**Issue by benjaminhenkel** [sgmap/tps#589]
![capture d ecran 2017-07-12 a 11 46 31](https://user-images.githubusercontent.com/28590367/28112445-55084bcc-66f9-11e7-9bc1-eb694a830e57.png)

**Comment by benjaminhenkel** [comment]
![capture d ecran 2017-07-12 a 11 26 00](https://user-images.githubusercontent.com/28590367/28112465-680b77e4-66f9-11e7-9243-46cf21dd9076.png)
Précision : sous Chrome il y en a un, mais pas sous firefox, safari, ou explorer

**Comment by benjaminhenkel** [comment]
A Haut-de-Seine

**Comment by mmagn** [comment]
Pour CNDP

**Comment by mmagn** [comment]
Pour sortir dans l'API une date clean il faut : 
- [ ] faire tourner un script qui passe toutes les dates dans le format ISO
- [ ] cleaner manuellement le reste des données dans des formats exotiques (une vingtaine)

Pour éviter à nouveau la pollution des données il faut :
- [ ] autoriser aux utilisateurs de saisir uniquement au format ISO et `dd/mm/yyyy`
- [ ] effectuer un formatage au `before_save` pour passer au format ISO
