### ISSUE TITLE
Supprimer les html_safe au profit de sanitize

### ISSUE THREAD

**Issue by LeSim** [sgmap/tps#592]
La fonction `html_safe` permet d'afficher du code html de manière non échappée.
Problème : il est possible alors d'utiliser les champs non échappés pour réaliser des attaques XSS.

Rails [suggère](https://apidock.com/rails/String/html_safe) d'utiliser `sanitize` au lieu de `html_safe`.
Sanitize laisse, par défaut, passer [les bons tags](https://github.com/rails/rails-html-sanitizer/blob/master/lib/rails/html/sanitizer.rb#L107).

A noter, par ailleurs, que dans notre projet, haml échappe les valeurs insérer par l'opérateur `=`.

**Comment by gregoirenovel** [comment]
Fait partiellement avec #590

**Comment by gregoirenovel** [comment]
À communiquer : Ministère de l'Environnement, de l'Énergie et de la Mer (JP L)
