### ISSUE TITLE
[RGS] Développer une supervision qui remontera automatiquement aux membres de l'équipe, une procédure publiée comportant des champs avec des mots clés interdits 

### ISSUE THREAD

**Issue by benjaminhenkel** [sgmap/tps#671]
Pour répondre à l'objectif de limiter les risques de collectes de données illégitimes (risque inacceptable)

**Comment by emsnytech** [comment]
On a le cas de figure avec le formulaire de l'ADA ...

**Comment by mmagn** [comment]
Duplicate https://github.com/sgmap/tps/issues/1097
