### ISSUE TITLE
ETQ accompagnateur, je souhaiterai pouvoir trier le tableau des procédures sur les états de façons a avoir une vue rapide des démarches à ouvrir

### ISSUE THREAD

**Issue by emsnytech** [sgmap/tps#774]
A la présentation de la liste des démarches, si celle ci est longue, je suis obligé de scroller la page pour voir là où il y a des points oranges...
Je voudrais avoir une information rapide sur le nombre de démarches concernés par des modifications.

**Comment by LeSim** [comment]
copie de #803 #804
