### ISSUE TITLE
Envoyer un email d'accusé de réception dès qu'un brouillon est enregistré pour que les gens le retrouvent

### ISSUE THREAD

**Issue by icollombet** [sgmap/tps#813]
* Problème : les utilisateurs cliquent souvent sur le lien pour créer un nouveau dossier au lieu de se connecter à leur compte pour retrouver leurs brouillons. Solution : envoyer un email avec un lien dès qu'un brouillon est créé (i.e. au moment où l'utilisateur accède à la page d'identification personnelle/SIRET).

Texte

Bonjour,
Votre dossier nº --numero_dossier-- a bien été enregistré comme brouillon sur la plateforme TéléProcédure Simplifiée. Vous pouvez le compléter en cliquant sur le lien suivant : --lien_dossier--.
Bonne journée,
L'équipe Téléprocédure Simplifiée

**Comment by mmagn** [comment]
Tester une autre solution au même problème : 
- Quand un utilisateur arrive sur une procédure lui indiquer si il a déjà des dossiers ou des brouillons sur cette procédure. (cette solution a l'avantage de fonctionner, même si l'utilisateur n'a pas vu dans sa boite mail qu'il avait un brouillon)

**Comment by gregoirenovel** [comment]
Il y a déjà une issue pour ta suggestion (#314), mais avec Ivan on pense que la solution proposée ici est plus rapide à implémenter (et on peut alors limiter l'implem de #314 au nouveau design)

**Comment by mmagn** [comment]
Ok après discussion on re-bascule sur la solution du mail.
