### ISSUE TITLE
Mauvais affichage des emails automatiques

### ISSUE THREAD

**Issue by mmagn** [sgmap/tps#890]
Rencontré avec un paragraphe en italique 
<img width="514" alt="capture d ecran 2017-10-20 a 18 13 35" src="https://user-images.githubusercontent.com/847942/31831094-895b5064-b5c2-11e7-8058-4281bb0132db.png">
(proc : 822 en prod)

**Comment by gregoirenovel** [comment]
À communiquer : MEL
