### ISSUE TITLE
Dans la messagerie, mauvais affichage de la signature

### ISSUE THREAD

**Issue by gregoirenovel** [sgmap/tps#906]
Cf. référence ci-dessous pour un exemple (voir barre d'adresse)

![messagerie petee](https://user-images.githubusercontent.com/1333173/31899446-e17104be-b81b-11e7-9d4b-c670f050c473.JPG)

À communiquer : MEL

**Comment by LeSim** [comment]
non reproduit, supposé fixé par #915
