### ISSUE TITLE
Utiliser /demarches au lieu de /procedures dans les URLs de la nouvelle UI ?

### ISSUE THREAD

**Issue by gregoirenovel** [sgmap/tps#911]
Ça va à l'encontre de notre [vocabulaire actuel](https://github.com/sgmap/tps/wiki/Vocabulaire), mais vu les renommage probable du produit, ne vaut-il pas mieux changer les URLs tout de suite ?

**Comment by mmagn** [comment]
Je clos, on a abordé le sujet "procédures" parle plus à l'admin, "démarches" à l'usager
