### ISSUE TITLE
Enrichir les informations remontées lors du remplissage d'un champ "Dossier lié"

### ISSUE THREAD

**Issue by icollombet** [sgmap/tps#99]
Coté usager, lors du remplissage du champ "dossier lié" du formulaire, rajouter date + nom procédure + organisme au message qui s'affiche quand on rentre un numéro de dossier dans le champ.

---

### Historique

@icollombet :

> ACTUEL lorsqu'un formulaire comporte un champ "Lien vers un autre dossier", cela fonctionnne de la façon suivante :
> - lorsque l'usager entre un numéro de dossier, la mention suivante est affichée (i) si le dossier existe "ce dossier répond à la procédure : ICPE" (ii) si le dossier n'existe pas "ce dossier est inconnu"
> - dans la vue dossier, la mention suivante est affichée (i) si le dossier existe "[Libellé du champ] : [nom de la procédure & lien vers le numéro de dossier]"
> 
> PROPOSITIONS
> - afficher dans le formulaire en ligne lorsque le dossier est connu
Ce dossier a été déposé le [date de soumission en français] sur la procédure "[titre de la procédure]" gérée par l'organisme [nom de l'organisme SI le nom de l'organisme a bien été renseigné].
> - afficher dans le formulaire en ligne lorsque le dossier est connu (ajouter point et majuscule)
Ce dossier est inconnu.

@gregoirenovel :

> Après discussions avec Ivan ce matin :
> 
> coté usager lors du remplissage du formulaire, rajouter date + nom procédure + organisme
> coté usager et admin, dans le résumé du dossier, ajouter ID + date + organisme

@gregoirenovel :

Séparation en l'issue actuelle + #133

**Comment by gregoirenovel** [comment]
Après discussions avec Ivan ce matin :
- coté usager lors du remplissage du formulaire, rajouter date + nom procédure + organisme
- coté usager et admin, dans le résumé du dossier, ajouter ID + date + organisme
